Corrected logic in EnsureToolPath
sillsdev/SIL.BuildTasks pull request #22
Opened 2019-09-26 15:55 UTC by tombogle

The fix was specifically to the part of the logic that looks for nunit-console in ProgramFiles.

Refactoring to simplify logic for other parts of that method
Added output (to console) to make it easier to see where it looked for and/or found the nunit-console program to run.

2019-09-26 16:24 UTC, ermshiperete requested changes
A few suggestions.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-:-LpiNtSh0as7_XEPGIyt:b7vh46j)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[SIL.BuildTasks/UnitTestTasks/NUnit.cs, line 242 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiLL58DNUY-Uyl5jzN:-LpiLL58DNUY-Uyl5jzO:b-ees4p2) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/NUnit.cs#L242)):*
> ```Smalltalk
> 			if (!string.IsNullOrEmpty(OutputXmlFile))
> 				bldr.AppendFormat(" \"--xml={0}\"", OutputXmlFile);
> 			bldr.Append(" --labels"); 
> ```

Extra space at end of line
___
*[SIL.BuildTasks/UnitTestTasks/NUnit.cs, line 251 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiMFR_AvXSEZ9gUiHv:-LpiMFR_AvXSEZ9gUiHw:bjiasop) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/NUnit.cs#L251)):*
> ```Smalltalk
> 				File.Exists(Path.Combine(ToolPath, RealProgramName)))
> 			{
> 				Console.WriteLine($"{nameof(EnsureToolPath)}: existing {nameof(ToolPath)} valid: {ToolPath}");
> ```

I think it would be better to use `Log.LogMessage` instead of `Console.WriteLine` (same for other places).
___
*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 228 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiNFB_9P1o2gB9xl8E:-LpiNFB_9P1o2gB9xl8F:b9691kn) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L228)):*
> ```Smalltalk
> 					$"({process.StartInfo.Arguments}) in {process.StartInfo.WorkingDirectory}";
> 
> 				Console.WriteLine(msg);
> ```

If you think that it's important to see this message, we probably should change to `MessageImportance.Normal`, or adjust the verbosity of the build job (`msbuild ... -verbosity:normal` (or `-verbosity:detailed`).


<!-- Sent from Reviewable.io -->

2019-09-27 19:11 UTC, tombogle commented
___
*[SIL.BuildTasks/UnitTestTasks/NUnit.cs, line 251 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiMFR_AvXSEZ9gUiHv:-Lpo4RIkDhVJ0F2LACz5:b-lhasyg) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/NUnit.cs#L251)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I think it would be better to use `Log.LogMessage` instead of `Console.WriteLine` (same for other places).
</blockquote></details>

I was thinking that the log messages were not coming out, but now I realize that I just need to increase verbosity to see them.


<!-- Sent from Reviewable.io -->

2019-09-27 19:16 UTC, tombogle commented
___
*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 228 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiNFB_9P1o2gB9xl8E:-Lpo8_ZA08wzbWRziW7L:b-9dahba) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L228)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

If you think that it's important to see this message, we probably should change to `MessageImportance.Normal`, or adjust the verbosity of the build job (`msbuild ... -verbosity:normal` (or `-verbosity:detailed`).
</blockquote></details>

I see how this works now. It's possible that my other fixes will solve the problem on TC. If not, I can change the verbosity there and maybe see what's going on.


<!-- Sent from Reviewable.io -->

2019-09-27 19:18 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ermshiperete)

___
*[SIL.BuildTasks/UnitTestTasks/NUnit.cs, line 242 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiLL58DNUY-Uyl5jzN:-Lpo4QRY39VftuX1TIM0:b-896fix) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/NUnit.cs#L242)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Extra space at end of line
</blockquote></details>

Done.
___
*[SIL.BuildTasks/UnitTestTasks/NUnit.cs, line 251 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/22#-LpiMFR_AvXSEZ9gUiHv:-Lpo8SyY66kM2EdmpraY:b-896fix) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/27e1887d90cbc8a4ed4931fc7fdfa5dd28d59998/SIL.BuildTasks/UnitTestTasks/NUnit.cs#L251)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I was thinking that the log messages were not coming out, but now I realize that I just need to increase verbosity to see them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-27 20:41 UTC, merged