Add NormalizeLocales task
sillsdev/SIL.BuildTasks pull request #25
Opened 2020-04-09 20:47 UTC by jasonleenaylor

* Add task to help work with Crowdin locales
* Add MockBuildEngine to support testing
* Add task into the documentation

2020-04-14 19:29 UTC, papeh reviewed
This code was designed for translations exported to
`/%locale%/**/filename.%locale%.ext`
however, the present `translation: "Chorus.%locale%.xlf"` will automatically export to
`/%normalized_locale%/%original_path%/Chorus.%locale%.xlf`
which this code will happily not normalize.

We'll need something similar to
```
foreach (var locale in locales.Where(l => !l.Contains('-')))
    // navigate the directory tree and strip region codes
```
(no longer a need to handle Chinese specifically).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/25#-:-M4u6XXO-Zh-3CUC2442:b-g4jku8)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ermshiperete)



<!-- Sent from Reviewable.io -->

2020-04-15 03:56 UTC, jasonleenaylor commented
@papeh Have you looked at the settings in Crowdin for the SIL Common Libraries recently? I think I already changed it to what this code expects so we can use the same task in both FieldWorks and the Common libraries. I intend to use this *before* generating the NuGet packages.





<!-- Sent from Reviewable.io -->

2020-04-15 12:21 UTC, ermshiperete requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Should add an entry to CHANGELOG.md though.

And it would be good to add `+semver:minor` to the git commit message.

2020-04-15 12:21 UTC, ermshiperete commented on SIL.BuildTasks.Tests/NormalizeLocalesTests.cs
> +			// Verify that the locale that needed to be normalized has been
is there a word missing? `...has been`?

2020-04-15 15:30 UTC, jasonleenaylor commented on SIL.BuildTasks.Tests/NormalizeLocalesTests.cs
> +			// Verify that the locale that needed to be normalized has been
It is grammatical in English. But I'll change it to make it parse easier. :)

2020-04-15 16:08 UTC, ermshiperete approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/25#-:-M4ya03g1MusW3XXiNxJ:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-15 16:19 UTC, merged