Support Keep a Changelog format input
sillsdev/SIL.BuildTasks pull request #40
Opened 2020-12-09 20:39 UTC by marksvc

- SIL.ReleaseTasks expected a different format of changelog. Support
keepachangelog.com style changelogs as well, which have a preamble,
[Unreleased] version, and sub-headings for types of changes (eg
"Added", "Changed", ...).
- Remove the preamble and [Unreleased] heading, to not carry those
thru to the user.
- There is some unfortunate mixing of string, string[], and
List<string> that could use some smoothing out.

2020-12-10 10:02 UTC, ermshiperete requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40)* status: all files reviewed, 7 unresolved discussions (waiting on @marksvc)

___
*[SIL.ReleaseTasks/CreateChangelogEntry.cs, line 33 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOAt_5ZB5ZPMEEvFMRx:-MOAt_5_CcApBS-6qPXk:bj7r3op) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/CreateChangelogEntry.cs#L33)):*
> ```Smalltalk
> 		public string DebianChangelog { get; set; }
> 
> 		public string Distribution { get; set; } = "UNRELEASED";
> ```

Yeah, I like that! :+1: 

Although there's the slight chance that the caller sets it to null or the empty string which would override the initialized value. But garbage in - garbage out, so I think this is acceptable.
___
*[SIL.ReleaseTasks/CreateChangelogEntry.cs, line 67 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOAuTBs3WSUHq-jLY4f:-MOAuTBs3WSUHq-jLY4g:b88240x) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/CreateChangelogEntry.cs#L67)):*
> ```Smalltalk
> 		{
> 			string mdText = string.Join("\n", markdownLines);
> 			bool isKAC = CreateReleaseNotesHtml.RemoveKACHeadIfPresent(ref mdText);
> ```

What's KAC?  Oh, I see, it's mentioned in the comment on `RemoveKACHeadIfPresent`.  And I understand that you don't want to rename that method to `RemoveKeepAChangelogHeadIfPresent`.

But it might help to rename the variable here to `isKeepAChangelog` or `isKeepAChangelogFormat` - IMO this would make it easier to make the connection between KAC and Keep A Changelog.
___
*[SIL.ReleaseTasks/CreateChangelogEntry.cs, line 83 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOAwU2YAS2t43Vp8fpf:-MOAwU2YAS2t43Vp8fpg:b7tq5mc) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/CreateChangelogEntry.cs#L83)):*
> ```Smalltalk
> 			// Skip a beginning blank line after the version header, if present.
> 			int contentStartingLineAfterVersionHeader = 1;
> 			if (string.IsNullOrWhiteSpace(markdownLines[1]))
> ```

What's with markdownLines[0] ? I thought we removed the header a few lines above?
___
*[SIL.ReleaseTasks/StampChangelogFileWithVersion.cs, line 44 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB-D-z5Xi48Tj9b82p:-MOB-D-z5Xi48Tj9b82q:b-hu2eng) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/StampChangelogFileWithVersion.cs#L44)):*
> ```Smalltalk
> 			{
> 				AddNewVersionToKAC(markdownLines);
> 			} else {
> ```

nit: inconsistent formatting
___
*[SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs, line 58 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB0UP-7ohpcomoWakN:-MOB0UP-7ohpcomoWakO:b-ta5pll) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs#L58)):*
> ```Smalltalk
> 				var newContents = File.ReadAllLines(changeLogFile);
> 				string newContentsText = string.Join("\n", newContents);
> 				Assert.That(newContentsText, Is.EqualTo(expectedDebianChangelog));
> ```

Won't this fail on Windows? Since the source file gets checked out with \r\n on Windows I'd expect `expectedDebianChangelog` to contain that as well...

I guess you could work around this problem by using `var newContents = File.ReadAllText(changeLogFile);`
___
*[SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs, line 71 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB1G9R1klMHQWi8-s9:-MOB1G9R1klMHQWi8-sA:b-2h109z) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs#L71)):*
> ```Smalltalk
> 
> 			string changelogContent =
> @"All notable changes to this project will be documented in this file.
> ```

At least some changelog files start with `# Change Log` - might be good to add this here as well (same in the other test files).
___
*[SIL.ReleaseTasks.Tests/StampChangelogFileWithVersionTests.cs, line 112 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB4OW-7WbJNg4mI4FQ:-MOB4OW-7WbJNg4mI4FR:b-8o1dlj) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/StampChangelogFileWithVersionTests.cs#L112)):*
> ```Smalltalk
> - All bugs.".Split('\n');
> 				int newExpectedHeadingLine = 17 - 1;
> 				expectedNewChangelogContent[newExpectedHeadingLine] = $"## [2.3.10] - {DateTime.Today.ToString("yyyy-MM-dd")}";
> ```

nit: Wouldn't it be easier to use `string.Replace("DATE_HERE", ...)` and then do `string.Split('\n')` (or leave `expectedNewChangelogContent` as a string and use `File.ReadAllText` below)?


<!-- Sent from Reviewable.io -->

2020-12-10 19:42 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40)* status: all files reviewed, 4 unresolved discussions (waiting on @ermshiperete)

___
*[SIL.ReleaseTasks/CreateChangelogEntry.cs, line 67 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOAuTBs3WSUHq-jLY4f:-MOD0PTq6msVApHNO3ei:bxxj0o2) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/CreateChangelogEntry.cs#L67)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

What's KAC?  Oh, I see, it's mentioned in the comment on `RemoveKACHeadIfPresent`.  And I understand that you don't want to rename that method to `RemoveKeepAChangelogHeadIfPresent`.

But it might help to rename the variable here to `isKeepAChangelog` or `isKeepAChangelogFormat` - IMO this would make it easier to make the connection between KAC and Keep A Changelog.
</blockquote></details>

Thank you. I ended up expanding most "KAC" usages, with only a couple left.
___
*[SIL.ReleaseTasks/CreateChangelogEntry.cs, line 83 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOAwU2YAS2t43Vp8fpf:-MOD1j9ABXW2OiFF7D6B:bms3pp1) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks/CreateChangelogEntry.cs#L83)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

What's with markdownLines[0] ? I thought we removed the header a few lines above?
</blockquote></details>

Right. I am adding a comment to hopefully make it a bit more clear. So the Keep a Changelog preamble gets removed, but there is still a version header. Once the KAC preamble is removed, the data is similar to the previous style of changelog. And we have a version header at the (new) top that we need to remove. 
___
*[SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs, line 58 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB0UP-7ohpcomoWakN:-MOD3m0w8mW7Ut9o_UaC:b-896fix) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs#L58)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Won't this fail on Windows? Since the source file gets checked out with \r\n on Windows I'd expect `expectedDebianChangelog` to contain that as well...

I guess you could work around this problem by using `var newContents = File.ReadAllText(changeLogFile);`
</blockquote></details>

Done.
___
*[SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs, line 71 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB1G9R1klMHQWi8-s9:-MOD5it_4PcAh6D7_iV1:b-mbcpfk) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/CreateChangelogEntryTests.cs#L71)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

At least some changelog files start with `# Change Log` - might be good to add this here as well (same in the other test files).
</blockquote></details>

Good thinking.
___
*[SIL.ReleaseTasks.Tests/StampChangelogFileWithVersionTests.cs, line 112 at r1](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-MOB4OW-7WbJNg4mI4FQ:-MOD5eIm7xI0oJF5-Sph:b-9755fa) ([raw file](https://github.com/sillsdev/sil.buildtasks/blob/09fc73463b024baf3ba19ee90e025db5f8e1d5c7/SIL.ReleaseTasks.Tests/StampChangelogFileWithVersionTests.cs#L112)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

nit: Wouldn't it be easier to use `string.Replace("DATE_HERE", ...)` and then do `string.Split('\n')` (or leave `expectedNewChangelogContent` as a string and use `File.ReadAllText` below)?
</blockquote></details>

Thank you.


<!-- Sent from Reviewable.io -->

2020-12-11 08:27 UTC, ermshiperete approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, but note the test failure on Jenkins (https://jenkins.lsdev.sil.org/view/Libraries/view/All/job/SIL.BuildTasks/view/change-requests/job/PR-40/3/execution/node/76/log/). Note that this happens on Windows (which got me confused at first, but the job builds on both Windows and Linux and combines the test results). It looks like `markDownTransformer.Transform()` always uses `\n`?

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-:-MOFrfxa6dJaIbsC-VSg:b-ybwhf0)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-11 09:00 UTC, ermshiperete approved these changes
Please add an entry to `CHANGELOG.md`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/sil.buildtasks/40#-:-MOG0qfH8raG6abkHq8A:bp2jt7)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-11 17:12 UTC, marksvc commented
I am converting the output from MarkdownDeep to platform newlines, which seemed like a good solution. 
I had a peek in the MarkdownDeep source and it does in fact use \n where I was looking.

2021-02-24 15:05 UTC, merged